# Generated by Django 4.1.7 on 2023-04-18 22:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_historicaluser_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluser',
            name='identification_number',
            field=models.CharField(blank=True, db_index=True, help_text='Número de identificación sin puntos ni guiones', max_length=20, validators=[django.core.validators.RegexValidator(code='invalid_identification_number', message='El número de identificación debe ser solo números y letras sin puntos, guiones o espacios.', regex='^\\w+$')], verbose_name='Número de identificación'),
        ),
        migrations.AlterField(
            model_name='user',
            name='identification_number',
            field=models.CharField(blank=True, help_text='Número de identificación sin puntos ni guiones', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_identification_number', message='El número de identificación debe ser solo números y letras sin puntos, guiones o espacios.', regex='^\\w+$')], verbose_name='Número de identificación'),
        ),
    ]
