# Generated by Django 4.1.7 on 2023-05-08 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_historicaluser_identification_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluser',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into the admin site.', verbose_name='Staff'),
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Administrador'), (2, 'Profesor'), (3, 'Director de escuela')], default=1, verbose_name='Rol'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into the admin site.', verbose_name='Staff'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Administrador'), (2, 'Profesor'), (3, 'Director de escuela')], default=1, verbose_name='Rol'),
        ),
    ]
