# Generated by Django 4.1.7 on 2023-03-21 13:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('requests', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('deleted_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de eliminación')),
                ('status', models.CharField(choices=[('COMPLETADO', 'Completado'), ('PENDIENTE', 'Pendiente'), ('SIN RESPUESTA', 'Sin Respuesta')], default='PENDIENTE', max_length=20, verbose_name='Estado de la Tarea')),
                ('topic', models.CharField(max_length=100, verbose_name='Tema de la Tarea')),
                ('details', models.TextField(max_length=500, verbose_name='Detalles de la Tarea')),
                ('time_spent', models.IntegerField(default=0, verbose_name='Tiempo invertido')),
                ('scheduled_date', models.DateField(verbose_name='Fecha programada')),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='homework', to='requests.request')),
            ],
            options={
                'verbose_name': 'Modelo compartido con registro histórico',
                'verbose_name_plural': 'Modelos compartidos con registros históricos',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricalHomework',
            fields=[
                ('id', models.BigIntegerField(blank=True, db_index=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de creación')),
                ('modified_date', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de modificación')),
                ('deleted_date', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Fecha de eliminación')),
                ('status', models.CharField(choices=[('COMPLETADO', 'Completado'), ('PENDIENTE', 'Pendiente'), ('SIN RESPUESTA', 'Sin Respuesta')], default='PENDIENTE', max_length=20, verbose_name='Estado de la Tarea')),
                ('topic', models.CharField(max_length=100, verbose_name='Tema de la Tarea')),
                ('details', models.TextField(max_length=500, verbose_name='Detalles de la Tarea')),
                ('time_spent', models.IntegerField(default=0, verbose_name='Tiempo invertido')),
                ('scheduled_date', models.DateField(verbose_name='Fecha programada')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='requests.request')),
            ],
            options={
                'verbose_name': 'historical Modelo compartido con registro histórico',
                'verbose_name_plural': 'historical Modelos compartidos con registros históricos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
