#!/bin/bash

set -o errexit
set -o nounset

worker_ready() {
  python -m celery -A config inspect ping
}

until worker_ready; do
  >&2 echo 'Celery workers not available'
  sleep 1
done
>&2 echo 'Celery workers is available'

python -m celery -A config  \
  --broker="${CELERY_BROKER_URL}" \
  flower
