# Generated by Django 4.1.7 on 2023-05-15 09:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homeworks', '0001_initial'),
        ('teachers', '0005_historicalscheduleslot_is_free_scheduleslot_is_free'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalEvent',
            fields=[
                ('id', models.BigIntegerField(blank=True, db_index=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de creación')),
                ('modified_date', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de modificación')),
                ('deleted_date', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Fecha de eliminación')),
                ('summary', models.CharField(max_length=100, verbose_name='Resumen')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='Descripción')),
                ('start_time', models.DateTimeField(verbose_name='Fecha de inicio')),
                ('end_time', models.DateTimeField(verbose_name='Fecha de fin')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('homework', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='homeworks.homework')),
                ('schedule_slot', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='teachers.scheduleslot')),
            ],
            options={
                'verbose_name': 'historical Modelo compartido con registro histórico',
                'verbose_name_plural': 'historical Modelos compartidos con registros históricos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('deleted_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de eliminación')),
                ('summary', models.CharField(max_length=100, verbose_name='Resumen')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='Descripción')),
                ('start_time', models.DateTimeField(verbose_name='Fecha de inicio')),
                ('end_time', models.DateTimeField(verbose_name='Fecha de fin')),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='homeworks.homework')),
                ('schedule_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='teachers.scheduleslot')),
            ],
            options={
                'verbose_name': 'Modelo compartido con registro histórico',
                'verbose_name_plural': 'Modelos compartidos con registros históricos',
                'abstract': False,
            },
        ),
    ]
