# Generated by Django 4.1.7 on 2023-05-09 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_alter_schoolmanager_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolmanager',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_managers', to='schools.school'),
        ),
    ]
