# Generated by Django 4.1.7 on 2023-05-09 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalrequest',
            name='request_type',
            field=models.CharField(choices=[('TAREAS', 'Apoyo en Tareas'), ('REFUERZO', 'Refuerzo Académico'), ('CUALQUIERA', 'Cualquiera')], default='TAREAS', max_length=20),
        ),
        migrations.AlterField(
            model_name='request',
            name='request_type',
            field=models.CharField(choices=[('TAREAS', 'Apoyo en Tareas'), ('REFUERZO', 'Refuerzo Académico'), ('CUALQUIERA', 'Cualquiera')], default='TAREAS', max_length=20),
        ),
    ]
