# Generated by Django 4.1.7 on 2023-03-28 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalschedule',
            name='day',
            field=models.CharField(choices=[('LUNES', 'Lunes'), ('MARTES', 'Martes'), ('MIERCOLES', 'Miércoles'), ('JUEVES', 'Jueves'), ('VIERNES', 'Viernes'), ('SABADO', 'Sábado'), ('DOMINGO', 'Domingo')], default='LUNES', max_length=10, verbose_name='Día'),
        ),
        migrations.AlterField(
            model_name='historicalschedule',
            name='request_type',
            field=models.CharField(choices=[('TAREAS', 'Apoyo en Tareas'), ('REFUERZO', 'Refuerzo Académico')], default='TAREAS', max_length=10, verbose_name='Tipo de solicitud'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='day',
            field=models.CharField(choices=[('LUNES', 'Lunes'), ('MARTES', 'Martes'), ('MIERCOLES', 'Miércoles'), ('JUEVES', 'Jueves'), ('VIERNES', 'Viernes'), ('SABADO', 'Sábado'), ('DOMINGO', 'Domingo')], default='LUNES', max_length=10, verbose_name='Día'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='request_type',
            field=models.CharField(choices=[('TAREAS', 'Apoyo en Tareas'), ('REFUERZO', 'Refuerzo Académico')], default='TAREAS', max_length=10, verbose_name='Tipo de solicitud'),
        ),
    ]
