# Generated by Django 4.1.7 on 2023-05-09 06:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("teachers", "0002_alter_historicalschedule_day_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalschedule",
            name="day",
        ),
        migrations.RemoveField(
            model_name="historicalschedule",
            name="end_hour",
        ),
        migrations.RemoveField(
            model_name="historicalschedule",
            name="start_hour",
        ),
        migrations.RemoveField(
            model_name="schedule",
            name="day",
        ),
        migrations.RemoveField(
            model_name="schedule",
            name="end_hour",
        ),
        migrations.RemoveField(
            model_name="schedule",
            name="start_hour",
        ),
        migrations.AddField(
            model_name="historicalschedule",
            name="day_of_week",
            field=models.CharField(
                choices=[
                    ("LUNES", "Lunes"),
                    ("MARTES", "Martes"),
                    ("MIERCOLES", "Miércoles"),
                    ("JUEVES", "Jueves"),
                    ("VIERNES", "Viernes"),
                    ("SABADO", "Sábado"),
                    ("DOMINGO", "Domingo"),
                ],
                default="LUNES",
                max_length=10,
                verbose_name="Día de la semana",
            ),
        ),
        migrations.AddField(
            model_name="historicalschedule",
            name="end_time",
            field=models.TimeField(
                default="12:00", verbose_name="Tiempo de finalización"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicalschedule",
            name="start_time",
            field=models.TimeField(default="12:00", verbose_name="Tiempo de inicio"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="schedule",
            name="day_of_week",
            field=models.CharField(
                choices=[
                    ("LUNES", "Lunes"),
                    ("MARTES", "Martes"),
                    ("MIERCOLES", "Miércoles"),
                    ("JUEVES", "Jueves"),
                    ("VIERNES", "Viernes"),
                    ("SABADO", "Sábado"),
                    ("DOMINGO", "Domingo"),
                ],
                default="LUNES",
                max_length=10,
                verbose_name="Día de la semana",
            ),
        ),
        migrations.AddField(
            model_name="schedule",
            name="end_time",
            field=models.TimeField(
                default="12:00", verbose_name="Tiempo de finalización"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="schedule",
            name="start_time",
            field=models.TimeField(default="12:00", verbose_name="Tiempo de inicio"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="historicalschedule",
            name="request_type",
            field=models.CharField(
                choices=[
                    ("TAREAS", "Apoyo en Tareas"),
                    ("REFUERZO", "Refuerzo Académico"),
                    ("CUALQUIERA", "Cualquiera"),
                ],
                default="TAREAS",
                max_length=10,
                verbose_name="Tipo de solicitud",
            ),
        ),
        migrations.AlterField(
            model_name="historicalschedule",
            name="teacher",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="teachers.teacher",
                verbose_name="Profesor",
            ),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="request_type",
            field=models.CharField(
                choices=[
                    ("TAREAS", "Apoyo en Tareas"),
                    ("REFUERZO", "Refuerzo Académico"),
                    ("CUALQUIERA", "Cualquiera"),
                ],
                default="TAREAS",
                max_length=10,
                verbose_name="Tipo de solicitud",
            ),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="schedules",
                to="teachers.teacher",
                verbose_name="Profesor",
            ),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teacher",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
