# Generated by Django 4.1.7 on 2023-05-15 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0004_scheduleslot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalscheduleslot',
            name='is_free',
            field=models.BooleanField(default=True, verbose_name='Espacio libre'),
        ),
        migrations.AddField(
            model_name='scheduleslot',
            name='is_free',
            field=models.BooleanField(default=True, verbose_name='Espacio libre'),
        ),
    ]
